name: plhydra

channels:
  - conda-forge
  - pytorch

dependencies:
  - pip
  - python=3.9
  - numpy
  - scipy
  - matplotlib
  - pytorch
  - torchvision
  - cudatoolkit
  - hydra-core 
  - pytorch-lightning 
  - plyfile
  - scikit-learn
  - tensorboard
  - pytest
  - sphinx
  - pip:
    - hydra-colorlog
#    - hydra-optuna-sweeper
#    - hydra-ax-sweeper
#    - hydra-ray-launcher
#    - hydra-submitit-launcher
