_target_: src.datamodule.dataset.PointCloudDataset

grid_size: 32
voxel_size: 0.1
scales: {1}
nb_pts_per_class: 1000
nb_classes: 9
testing: False
use_no_labels: False
use_class0: False
use_color: False
use_reflectance: True

datadir: ${data_dir}/parislille3d # used by other configs
class_names: ["ground","building","pole","bollard","trash can","barrier","pedestrian","car","natural"]