###############################################################################
NUM_WORKERS: 8 # Number of threads for pytorch Dataloader
DEVICE_ID: 0 # GPU id 

###############################################################################
USE_NO_LABELS: True
#USE_NO_LABELS: False
    
###############################################################################
BATCH_SIZE: 20