_target_: src.pl_datamodule.dataset.PointCloudDataset

grid_size: 32
voxel_size: 0.1
scales: {1}
nb_pts_per_class: 1000
nb_classes: 8
testing: False
use_no_labels: False
use_class0: False
use_color: True
use_reflectance: True

class_names: ["man-made terrain","natural terrain","high vegetation","low vegetation","buildings","hard scape","scanning artefacts","cars"]